services: 
  redis-series:
    image: redis:7-alpine
    container_name: redis-series
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    
  mongo-for-redis:
    image: mongo:7
    container_name: mondo-for-redis
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=redis-series
    volumes:
      - 'mongo-data:/data/db'
    
volumes:
  redis-data: {}
  mongo-data: {}